### ISSUE TITLE
Crash on game launch with Nestopia

### ISSUE THREAD

**Issue by athairus** [team-phoenix/Phoenix#179]
Core: `nestopia_libretro.dll`
Date: Oct 15  2014 
MD5: `b6a4370cc9f200b74271928726877ef8 `

Game: `BurgerTime (USA).nes`
MD5: `924f89aad439db0ada794e23075d649f`

Stack trace:
```
Thread 1 (Thread 33780.0x48ec):
#0  0x00007ff95d745506 in strrchr () from C:\Windows\system32\msvcrt.dll
No symbol table info available.
#1  0x000000004324e062 in retro_load_game () from C:\msys64\home\athairus\phoenix\build\win\frontend\Cores\nestopia_libretro.dll
No symbol table info available.
#2  0x000000000043e168 in Core::slotLoadGame (this=0x37752200, path=...) at ../../../phoenix/backend/core.cpp:206
        __PRETTY_FUNCTION__ = "void Core::slotLoadGame(QString)"
        gameInfo = {path = 0x0, data = 0x3e4cefc8, size = 24592, meta = 0x66e9cb <_ZN9__gnu_cxxL21__default_lock_policyE+7> ""}
        gamePathByteArray = {static MaxSize = 1073741800, d = 0x37acbe30}
#3  0x0000000000468188 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<QString>, void, void (Core::*)(QString)>::call (f=(void (Core::*)(Core * const, QString)) 0x43df22 <Core::slotLoadGame(QString)>, o=0x37752200, arg=0x238a30) at C:/msys64/mingw64/include/QtCore/qobjectdefs_impl.h:501
No locals.
#4  0x000000000046be0f in QtPrivate::FunctionPointer<void (Core::*)(QString)>::call<QtPrivate::List<QString>, void> (f=(void (Core::*)(Core * const, QString)) 0x43df22 <Core::slotLoadGame(QString)>, o=0x37752200, arg=0x238a30) at C:/msys64/mingw64/include/QtCore/qobjectdefs_impl.h:520
No locals.
#5  0x0000000000469e9d in QtPrivate::QSlotObject<void (Core::*)(QString), QtPrivate::List<QString>, void>::impl (which=1, this_=0x37753220, r=0x37752200, a=0x238a30, ret=0x0) at C:/msys64/mingw64/include/QtCore/qobject_impl.h:143
No locals.
#6  0x000000006958647e in QtPrivate::QSlotObjectBase::call (this=0x37753220, r=0x37752200, a=0x238a30) at ../../include/QtCore/../../src/corelib/kernel/qobject_impl.h:124
No locals.
#7  0x0000000069462179 in QMetaObject::activate (sender=0x377519d0, signalOffset=29, local_signal_index=1, argv=0x238a30) at kernel/qobject.cpp:3703
        obj = {d = 0x37753220}
        receiverInSameThread = true
        sw = {receiver = 0x37752200, previousSender = 0x0, currentSender = {sender = 0x377519d0, signal = 30, ref = 1}, switched = true}
        callFunction = 0x37753220
        receiver = 0x37752200
        method_relative = 47789
        c = 0x37753270
        last = 0x37753270
        locker = {val = 1769678816}
        connectionLists = {connectionLists = 0x37752b00}
        list = 0x37752d48
        signal_index = 30
        empty_argv = {0x0}
        currentThreadId = 0x48ec
        __PRETTY_FUNCTION__ = "static void QMetaObject::activate(QObject*, int, int, void**)"
#8  0x0000000069461a38 in QMetaObject::activate (sender=0x377519d0, m=0x475560 <VideoItem::staticMetaObject>, local_signal_index=1, argv=0x238a30) at kernel/qobject.cpp:3583
No locals.
#9  0x0000000000435b9a in VideoItem::signalLoadGame (this=0x377519d0, _t1=...) at moc/moc_videoitem.cpp:481
        _a = {0x0, 0x238a70}
#10 0x0000000000430b0c in VideoItem::setGame (this=0x377519d0, game=...) at ../../../phoenix/backend/videoitem.cpp:276
No locals.
#11 0x0000000000435844 in VideoItem::qt_static_metacall (_o=0x377519d0, _c=QMetaObject::WriteProperty, _id=1, _a=0x238c50) at moc/moc_videoitem.cpp:397
        _t = 0x377519d0
        _v = 0x238cc0
#12 0x0000000000435ab1 in VideoItem::qt_metacall (this=0x377519d0, _c=QMetaObject::WriteProperty, _id=1, _a=0x238c50) at moc/moc_videoitem.cpp:453
No locals.
#13 0x00000000694385e7 in QMetaObject::metacall (object=0x377519d0, cl=QMetaObject::WriteProperty, idx=42, argv=0x238c50) at kernel/qmetaobject.cpp:296
No locals.
#14 0x000000001041fe38 in QV4::QObjectWrapper::setProperty (object=0x377519d0, ctx=0x33cc1350, property=0x36467d08, value=...) at jsruntime/qv4qobjectwrapper.cpp:533
        o = {static null = {<No data fields>}, d = 0x3e6fc770}
        status = -1
        flags = 0
        argv = {0x238cc0, 0x0, 0x238cbc, 0x238cb8}
        newBinding = 0x0
        scope = {engine = 0x330b06b0, mark = 0x33cc1358, size = 1}
        f = {ptr = 0x33cc1358}
        oldBinding = 0x0
#15 0x00000000104209ec in QV4::QObjectWrapper::setProperty (this=0x33cc1348, ctx=0x33cc1350, propertyIndex=42, value=...) at jsruntime/qv4qobjectwrapper.cpp:669
        ddata = 0x376fe5f0
        cache = 0x36554e00
        property = 0x36467d08
#16 0x000000001043901a in QV4::Runtime::setQmlQObjectProperty (engine=0x330b06b0, object=..., propertyIndex=42, value=...) at jsruntime/qv4runtime.cpp:1403
        scope = {engine = 0x330b06b0, mark = 0x33cc1348, size = 2}
        wrapper = {ptr = 0x33cc1348}
        ctx = {ptr = 0x33cc1350}
#17 0x00000000385809c4 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

```

**Comment by athairus** [comment]
Can't reproduce with a debug build of Nestopia (https://github.com/libretro/nestopia/commit/ee46f4bab9a04ac1b34b35c1ebfa236eb04e0c21). Not sure that this is the revision that the crashing one is based on? It's the closest one without going over (2 days).

**Comment by athairus** [comment]
Issue was caused by [NstDatabase.xml](https://github.com/libretro/nestopia/blob/master/NstDatabase.xml) not being available and the code not handling that fact very well...
